spring:
  datasource:
    url: jdbc:mysql://192.168.28.130:3306/seata-demo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 1q2w3e4r
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    alibaba:
      seata:
        # seata 服务分组，要与服务端nacos-config.txt中service.vgroup_mapping的后缀对应，默认是${spring.application.name}-fescar-service-group
        tx-service-group: storage-service-group