spring:
  datasource:
    url: jdbc:mysql://${zlt.datasource.ip}:3306/file_center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${zlt.datasource.username}
    password: ${zlt.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.file.model
  global-config:
    db-config:
      id-type: INPUT

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.central.file.controller
  default-flat-param-object: true

knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 文件中心接口文档

zlt:
  file-server:
    type: s3
    #fdfs:
    #  web-url: ${zlt.fdfs.web-url}
    s3:
      access-key: ${zlt.s3.access-key}
      accessKeySecret: ${zlt.s3.accessKeySecret}
      endpoint: ${zlt.s3.endpoint}
      bucketName: ${zlt.s3.bucketName}
  #多租户配置
  tenant:
    enable: true

#fastDFS配置
#fdfs:
#  soTimeout: 1500
#  connectTimeout: 600
#  trackerList: ${zlt.fdfs.trackerList}