spring:
  datasource:
    url: jdbc:mysql://${zlt.datasource.ip}:3306/oauth-center?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${zlt.datasource.username}
    password: ${zlt.datasource.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.central.oauth.model
  global-config:
    db-config:
      id-type: auto

springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.central.oauth.controller

knife4j:
  enable: true
  setting:
    swagger-model-name: 认证中心接口文档

zlt:
  security:
    code:
      # 忽略验证码的应用编号
      ignoreClientCode: app
    auth:
      # 开启统一登出
      unifiedLogout: true
      # 同账号登录互踢
      isSingleLogin: true
  #多租户配置
  tenant:
    enable: true
    ignoreTables:
      - oauth_client_details
  # 数据权限
  datascope:
    enabled: false
    includeSqls:
      # 应用列表
      - com.central.oauth.mapper.ClientMapper.findList